services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    command: git config --global --add safe.directory /com.docker.devenvironments.code
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

